export interface BadgeDefinition {
  id: string;
  name: string;
  description: string;
  category: "building" | "streak" | "xp" | "quest" | "level";
  icon: string;
  requirement: string;
  requirementValue: number | null;
  requirementKey: string | null;
}

export const BADGE_DEFINITIONS: BadgeDefinition[] = [
  // ── Building badges (6) ──
  {
    id: "building_town_hall",
    name: "Town Mayor",
    description: "Unlock the Town Hall",
    category: "building",
    icon: "🏛️",
    requirement: "Unlock the Town Hall building",
    requirementValue: null,
    requirementKey: "town_hall",
  },
  {
    id: "building_school",
    name: "Scholar",
    description: "Unlock the School",
    category: "building",
    icon: "🏫",
    requirement: "Unlock the School building",
    requirementValue: null,
    requirementKey: "school",
  },
  {
    id: "building_library",
    name: "Bookworm",
    description: "Unlock the Library",
    category: "building",
    icon: "📚",
    requirement: "Unlock the Library building",
    requirementValue: null,
    requirementKey: "library",
  },
  {
    id: "building_inn",
    name: "Innkeeper",
    description: "Unlock the Inn",
    category: "building",
    icon: "🏠",
    requirement: "Unlock the Inn building",
    requirementValue: null,
    requirementKey: "inn",
  },
  {
    id: "building_chapel",
    name: "Priest",
    description: "Unlock the Chapel",
    category: "building",
    icon: "⛪",
    requirement: "Unlock the Chapel building",
    requirementValue: null,
    requirementKey: "chapel",
  },
  {
    id: "building_well",
    name: "Water Bearer",
    description: "Unlock the Well",
    category: "building",
    icon: "🪣",
    requirement: "Unlock the Well building",
    requirementValue: null,
    requirementKey: "well",
  },
  {
    id: "building_market",
    name: "Merchant",
    description: "Unlock the Market",
    category: "building",
    icon: "🏪",
    requirement: "Unlock the Market building",
    requirementValue: null,
    requirementKey: "market",
  },
  {
    id: "building_bakery",
    name: "Baker",
    description: "Unlock the Bakery",
    category: "building",
    icon: "🥖",
    requirement: "Unlock the Bakery building",
    requirementValue: null,
    requirementKey: "bakery",
  },

  // ── Streak badges (4) ──
  {
    id: "streak_3",
    name: "Getting Started",
    description: "3-day reading streak",
    category: "streak",
    icon: "🔥",
    requirement: "Maintain a 3-day reading streak",
    requirementValue: 3,
    requirementKey: null,
  },
  {
    id: "streak_7",
    name: "Week Warrior",
    description: "7-day reading streak",
    category: "streak",
    icon: "⚡",
    requirement: "Maintain a 7-day reading streak",
    requirementValue: 7,
    requirementKey: null,
  },
  {
    id: "streak_14",
    name: "Fortnight Force",
    description: "14-day reading streak",
    category: "streak",
    icon: "💫",
    requirement: "Maintain a 14-day reading streak",
    requirementValue: 14,
    requirementKey: null,
  },
  {
    id: "streak_30",
    name: "Monthly Master",
    description: "30-day reading streak",
    category: "streak",
    icon: "🌟",
    requirement: "Maintain a 30-day reading streak",
    requirementValue: 30,
    requirementKey: null,
  },

  // ── XP milestone badges (4) ──
  {
    id: "xp_100",
    name: "First Steps",
    description: "Earn 100 XP",
    category: "xp",
    icon: "✨",
    requirement: "Earn 100 XP total",
    requirementValue: 100,
    requirementKey: null,
  },
  {
    id: "xp_500",
    name: "XP Hunter",
    description: "Earn 500 XP",
    category: "xp",
    icon: "💎",
    requirement: "Earn 500 XP total",
    requirementValue: 500,
    requirementKey: null,
  },
  {
    id: "xp_1000",
    name: "XP Champion",
    description: "Earn 1000 XP",
    category: "xp",
    icon: "👑",
    requirement: "Earn 1000 XP total",
    requirementValue: 1000,
    requirementKey: null,
  },
  {
    id: "xp_2500",
    name: "Legendary",
    description: "Earn 1,200 XP",
    category: "xp",
    icon: "🏆",
    requirement: "Earn 1,200 XP total",
    requirementValue: 1200,
    requirementKey: null,
  },

  // ── Quest badges (4) ──
  {
    id: "quest_first_pass",
    name: "First Victory",
    description: "Pass your first quest",
    category: "quest",
    icon: "🎯",
    requirement: "Pass 1 quest",
    requirementValue: 1,
    requirementKey: null,
  },
  {
    id: "quest_10_passed",
    name: "Quest Tracker",
    description: "Pass 5 different quests",
    category: "quest",
    icon: "📜",
    requirement: "Pass 5 different quests",
    requirementValue: 5,
    requirementKey: null,
  },
  {
    id: "quest_25_passed",
    name: "Quest Master",
    description: "Pass all 8 quests",
    category: "quest",
    icon: "⚔️",
    requirement: "Pass all 8 quests",
    requirementValue: 8,
    requirementKey: null,
  },
  {
    id: "quest_perfect_first",
    name: "Perfectionist",
    description: "Perfect score on first try",
    category: "quest",
    icon: "💯",
    requirement: "Pass a quest on the first attempt",
    requirementValue: 1,
    requirementKey: "attempts_1",
  },

  // ── Reading level badges (4) ──
  {
    id: "level_2",
    name: "Rising Reader",
    description: "Placed at Reading Level 2 or above",
    category: "level",
    icon: "📖",
    requirement: "Be placed at reading level 2 or above",
    requirementValue: 2,
    requirementKey: null,
  },
  {
    id: "level_3",
    name: "Developing Reader",
    description: "Placed at Reading Level 3 or above",
    category: "level",
    icon: "📗",
    requirement: "Be placed at reading level 3 or above",
    requirementValue: 3,
    requirementKey: null,
  },
  {
    id: "level_4",
    name: "Fluent Reader",
    description: "Placed at Reading Level 4",
    category: "level",
    icon: "🎓",
    requirement: "Be placed at reading level 4",
    requirementValue: 4,
    requirementKey: null,
  },
];
